### PR TITLE
Explode iterator

### PR DESCRIPTION
**Pull request by tobya**
Hi 

I'm not sure if this is something you like, but I thought it would be fun to see if I could implement the explode function as an iterator.  It slightly breaks your model, but I think it works nicely.  I have added an example of how it works to the `demo.php` file.

```
/**
 * Can be used as an iterator after call to explode function
 */ 
 $string = new SimpleString('Lorem,ipsum,dolar,sit,amet,lorem,ipsum');
 foreach($string->explode(',') as $key => $value)
 {
   echo "<BR>Explode Value $key = $value";
 }
```

I know you want to keep your design really simple and every function should return a string so if you feel that this change doesn't fit in that's cool.  If you think its good then I'd like any  feedback to make it better, also I can add a test and documentation.

### CODE REVIEW

**Comment by tobya** [comment]
Seems I broke the build. Oops!

Not sure why though.

**Comment by tobya** [comment]
found error! an extra `public` keyword

**Comment by klaussilveira** [comment]
This is a very interesting feature, although i'm not sure if it fits SimpleString. It's too big as it is... however, i'm working on a new project that would be a perfect fit for this. Stay tuned. :+1:

**Comment by tobya** [comment]
Thanks, I'll keep an eye out for that

**Pull request closed without merging**
