### PR TITLE
just some minor ajusts according to the code-sniffer!

### PR DESCRIPTION
**Pull request by gutomaia**
Hey,

Now that you got a Continuos Integration server, it is time to make that information useful!

:D

### CODE REVIEW

**Comment by klaussilveira** [comment]
2 spaces for indentation? Why?

**Comment by gutomaia** [comment]
4 spaces!? nao foi 4 spaces?

Guto Maia
@gutomaia

2011/7/26 klaussilveira <
reply@reply.github.com>

**Comment by gutomaia** [comment]
Se no foi 4 spaces... nao aceita :D

Guto Maia
@gutomaia

2011/7/26 Guto Maia guto@guto.net

**Comment by gutomaia** [comment]
oxe...
ta doido !!!
olha ae... sao 4 espacos
https://raw.github.com/gutomaia/SimpleString/master/SimpleString.class.php

Guto Maia
@gutomaia

2011/7/26 Guto Maia guto@guto.net

**Comment by klaussilveira** [comment]
Estranho, o visualizador web do github mostrou 2! Shame on him! :O

**Pull request merged**
